#@IgnoreInspection BashAddShebang
#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# Set DEFAULT_USER for agnoster prompt
export DEFAULT_USER=$(whoami)

# history settings
export HISTSIZE=99999
export HISTFILESIZE=999999
export SAVEHIST=$HISTSIZE