#@IgnoreInspection BashAddShebang
#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export GOPATH=${HOME}/Develop/work/go-dev
export PATH=${PATH}:${GOPATH}/bin

AWSFUNCTIONS="${HOME}/Develop/work/aws-utils-scripts/awsFunctions.sh"

if [[ -s ${AWSFUNCTIONS} ]]; then
  source ${AWSFUNCTIONS}
fi
export AWS_ROLE=devops-admin
alias tmake="time gmake"
