#@IgnoreInspection BashAddShebang
#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export VAULT_ADDR=https://vault.devops.discovery.com
export DISCOCLI_CLOBBER=true

# add gopath
export GOPATH=${HOME}/Develop/work/go-dev
export PATH=${PATH}:${GOPATH}/bin


## Set up pyenv
#export PYENV_ROOT="$HOME/.pyenv"
#export PATH="$PYENV_ROOT/bin:$PATH"
#
#eval "$(pyenv init -)"
#eval "$(pyenv virtualenv-init -)"

export PIP_REQUIRE_VIRTUALENV=true

# declare AWS role
export AWS_ROLE=devops-admin

# source functions
AWSFUNCTIONS="${HOME}/Develop/work/aws-utils-scripts/awsFunctions.sh"
CONJURFUNCTIONS="${HOME}/Develop/work/aws-utils-scripts/conjurFunctions.sh"


if [[ -s ${AWSFUNCTIONS} ]]; then
  source ${AWSFUNCTIONS}
fi

if [[ -s ${CONJURFUNCTIONS} ]]; then
  source ${CONJURFUNCTIONS}
fi

# add iterm2 shell integration
ITERM2_SHELL_INTEGRATION="${HOME}/.iterm2_shell_integration.zsh"

if [[ -s ${ITERM2_SHELL_INTEGRATION} ]]; then
  source ${ITERM2_SHELL_INTEGRATION}
fi


# add minikube completion
if (( $+commands[minikube] )); then
  source <(minikube completion zsh)
fi

# add helm completion
if (( $+commands[helm] )); then
  source <(helm completion zsh)
fi


# add other completions
COMPLETION="${HOME}/.zsh/completion/"
if [[ -d ${COMPLETION} ]]; then
  fpath=(${COMPLETION} ${fpath})
  autoload -Uz compinit && compinit -i
fi

# add tmake function
tmake () {time gmake $1}

# aliases
alias pbc='cat ~/.btp | pbcopy'
alias pbp='pbpaste >| ~/.btp'
